[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar     = "x86_64-w64-mingw32-gcc-ar"

# If you also build 32-bit Windows:
# [target.i686-pc-windows-gnu]
# linker = "i686-w64-mingw32-gcc"
# ar     = "i686-w64-mingw32-gcc-ar"